import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "WEB tutorial",
  description: "Generated by create kingmo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          <li>
            <Link href="/read/1">HTML</Link>
          </li>
          <li>
            <Link href="/read/2">CSS</Link>
          </li>
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/id">Update</Link>
          </li>
          <li>
            <button>Delete</button>
          </li>
        </ul>
      </body>
    </html>
  );
}
